 const courses = [
    {
      title: "Web Development Bootcamp (Basic)",
      instructor: "John Doe",
      rating: 4.5,
      enrollments: 1200,
      duration: "6 weeks",
      price: "₹1,499",
      imageUrl: BasicWebDev,
      progress: 75,
      path: "/description",
    },
    {
      title: "React for Beginners",
      instructor: "Jane Smith",
      rating: 4.7,
      enrollments: 900,
      duration: "4 weeks",
      price: "₹1,999",
      imageUrl: reactForBeginnersImg,
      progress: 40,
      path: "/React",
    },
    {
      title: "Node.js Crash Course",
      instructor: "Alice Johnson",
      rating: 4.4,
      enrollments: 500,
      duration: "3 weeks",
      price: "₹999",
      imageUrl: NodeJs,
      progress: 20,
      path: "/node",
    },
  ];